title: Jacob Dy | Freelance Developer
logo: /assets/img/me.png
description: Jacob Dy is a freelance software developer and graphic artist.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal

# SocMed
social-network-links:
  email: "jacobmigueldy@gmail.com"
  facebook: dychosenone
  github: dychosenone

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
